### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [chtixof/minchat_ynh#2]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by magikcypress** [comment]
I approve what @frju365 says, if you could check the PR #4 that I just do and then send your app on the YunoHost group, it would be great!

Thank you

**Comment by chtixof** [comment]
Done. Sorry for the delay.

**Comment by frju365** [comment]
Thank you very much !

Normally you have the write right. If you need to create a team (to add new member) or if you need the admin rights, ask me to enable or reopen this issue. :smile: 
frju365
