### ISSUE TITLE
manifest translation' typo

### ISSUE THREAD

**Issue by Jibec** [chtixof/minchat_ynh#3]
hi, can you please fix your manifest?
there is two "en" keys:

                    "en": "Choose a domain for minchat",
                    "en": "Choisissez un domaine pour minchat"

                    "en": "Choose a path for minchat",
                    "en": "Choisissez un chemin pour minchat"

                    "en": "Is it a public site (Y)",
                    "en": "Taper Y si le site est public"

thanks for your help

**Comment by magikcypress** [comment]
Fixed with this PR #4

**Comment by Jibec** [comment]
thanks 👍
